### ISSUE TITLE
404 when trying to access post from main page

### ISSUE THREAD

**Issue by Arielgordon123** [greenpress/blog-front#24]
![image](https://user-images.githubusercontent.com/3001759/89729183-d9c95f00-da3b-11ea-87c8-93ec2d108c0b.png)

**Comment by davidmeirlevy** [comment]
Which theme you use?

**Comment by davidmeirlevy** [comment]
bug fixed on v1.0.9

try to use `greenpress upgrade` command to update your local blog.
