### ISSUE TITLE
Add reverse-proxy to the drafts-service

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/blog-front#35]
In production, all services are hidden from this gateway and should have a reverse-proxy to be exposed.
you can see that configured at the `config` file, that set the service exposed endpoints and port, and at the `api-proxy.js` file, that created the actual proxies to other services.

the drafts service must be configured here the same way.

**Comment by itays123** [comment]
will add it to my PR in a minute

**Comment by davidmeirlevy** [comment]
the frontend service also works as the application main gateway.
all requests are passing through it, and if it's a frontend thing, it renders the UI, or else it passes the request into the internal service.
all services are not exposed, and only the endpoints mention here are available to the outside world.

**Comment by itays123** [comment]
On it!
