### ISSUE TITLE
[Enhancement] ability to create a current theme shortcut to a global path

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/blog-front#37]
at `set-theme.js`:
https://github.com/greenpress/blog-front/blob/master/helpers/set-theme.js

the theme is given from an environment variable `THEME`.

if the value starts with "global:" -> then consider the rest of the value as a global path.
else -> use the current mechanism to the `themes` folder.

**Comment by franciscoemanuel** [comment]
Working on it!

**Comment by franciscoemanuel** [comment]
@davidmeirlevy I've created a PR (#38) for this issue.

**Comment by davidmeirlevy** [comment]
Thanks!
This issue has other linked issues inside the CLI:
https://github.com/greenpress/greenpress-cli/issues/37
